language: python
python: "3.6"

jobs:
  include:
    - stage: "Checks"
      name: "PyLint"
      script: python setup.py develop && ./ci/pylint.sh
    - # Same stage
      name: "Tests"
      script: python setup.py develop test
    - # Same stage
      name: "Docs build"
      script: python setup.py develop docs
